services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pg-admin:
    image: dpage/pgadmin4
    container_name: pg-admin
    env_file:
      - .env
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      postgres-db:
        condition: service_healthy

  main-service:
    build: ../modjot-main-service
    container_name: main-service
    depends_on:
      postgres-db:
        condition: service_healthy
      ai-service:
        condition: service_healthy
    env_file:
      - .env

  ai-service:
    build: ../modjot-ai-wrapper-service
    container_name: ai-service
    # depends_on:
    #   - modjot-ai
    env_file:
      - ../modjot-ai-wrapper-service/.env
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051", "-rpc-timeout=1s"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 5s
    ports:
      - "50051:50051"

  # modjot-ai:
  #   image: ollama/ollama:latest
  #   container_name: modjot-ai
  #   ports:
  #     - "${OLLAMA_PORT}:11434"
  #   volumes:
  #     - ./ollama:/app 
  #   entrypoint: ["/bin/bash", "/app/run_ollama.sh"]

  kong:
    image: kong:3.6
    container_name: kong
    depends_on:
      - main-service
      - pg-admin
    env_file:
      - .env
    volumes:
      - ./kong/kong.yml:/etc/kong/kong.yml:ro
    ports:
      - "80:8000"
      - "8001:8001"
      - "443:8443"

volumes:
  dbdata:
