services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pg-admin:
    image: dpage/pgadmin4
    container_name: pg-admin
    env_file:
      - .env
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      postgres-db:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"

  main-service:
    image: ghcr.io/cp25sy5-modjot/main-service:latest
    container_name: main-service
    depends_on:
      postgres-db:
        condition: service_healthy
      ai-service:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    volumes:
      - uploads:/uploads

  worker-service:
    image: ghcr.io/cp25sy5-modjot/main-service:latest
    container_name: worker-service
    depends_on:
      postgres-db:
        condition: service_healthy
      ai-service:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    command: ["/worker"]
    volumes:
      - uploads:/uploads

  ai-service:
    image: ghcr.io/cp25sy5-modjot/ai-wrapper-service:latest
    container_name: ai-service
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051", "-rpc-timeout=1s"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 5s
    ports:
      - "50051:50051"

  kong:
    image: kong:3.6
    container_name: kong
    depends_on:
      - main-service
      - pg-admin
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml
      - KONG_PROXY_LISTEN=0.0.0.0:8000,0.0.0.0:8443 ssl
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    volumes:
      - ./kong/kong.yml:/etc/kong/kong.yml:ro
    ports:
      - "80:8000"
      - "8001:8001"
      - "443:8443"

volumes:
  dbdata:
